<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Inizios-MacBook-Pro-2.local" ignored="0" name="Test" tests="3" failures="1" timestamp="2021-02-14T23:22:04 PST" time="17.576" errors="0">
  <testcase name="signinError" time="2.481" classname="homePageTestCases.VerifySignInErrorMessage"/>
  <testcase name="signinError1" time="2.136" classname="homePageTestCases.VerifySignInErrorMessage">
    <failure type="java.lang.AssertionError" message="error message is not expected expected [There ] but found [There was a problem]">
      <![CDATA[java.lang.AssertionError: error message is not expected expected [There ] but found [There was a problem]
at homePageTestCases.VerifySignInErrorMessage.signinError1(VerifySignInErrorMessage.java:32)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- signinError1 -->
  <testcase name="verifyHeader" time="0.495" classname="homePageTestCases.HomePageHeaderTestCase"/>
</testsuite> <!-- Test -->
