<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Inizios-MacBook-Pro-2.local" failures="1" tests="3" name="Test" time="17.124" errors="0" timestamp="2021-02-11T21:23:08 PST">
  <testcase classname="homePageTestCases.VerifySignInErrorMessage" name="signinError" time="2.519"/>
  <testcase classname="homePageTestCases.VerifySignInErrorMessage" name="signinError1" time="2.278">
    <failure type="java.lang.AssertionError" message="error message is not expected expected [There ] but found [There was a problem]">
      <![CDATA[java.lang.AssertionError: error message is not expected expected [There ] but found [There was a problem]
at homePageTestCases.VerifySignInErrorMessage.signinError1(VerifySignInErrorMessage.java:32)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- signinError1 -->
  <testcase classname="homePageTestCases.HomePageHeaderTestCase" name="verifyHeader" time="0.009"/>
</testsuite> <!-- Test -->
