<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-02-11T21:22:46 PST" name="Suite" finished-at="2021-02-11T21:23:03 PST" duration-ms="17124">
    <groups>
    </groups>
    <test started-at="2021-02-11T21:22:46 PST" name="Test" finished-at="2021-02-11T21:23:03 PST" duration-ms="17124">
      <class name="homePageTestCases.HomePageHeaderTestCase">
        <test-method is-config="true" signature="setupMethod()[pri:0, instance:homePageTestCases.HomePageHeaderTestCase@609db43b]" started-at="2021-02-11T21:23:00 PST" name="setupMethod" finished-at="2021-02-11T21:23:03 PST" duration-ms="3232" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupMethod -->
        <test-method signature="verifyHeader()[pri:0, instance:homePageTestCases.HomePageHeaderTestCase@609db43b]" started-at="2021-02-11T21:23:03 PST" name="verifyHeader" finished-at="2021-02-11T21:23:03 PST" duration-ms="9" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyHeader -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:homePageTestCases.HomePageHeaderTestCase@609db43b]" started-at="2021-02-11T21:23:03 PST" name="tearDown" finished-at="2021-02-11T21:23:03 PST" duration-ms="218" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- homePageTestCases.HomePageHeaderTestCase -->
      <class name="homePageTestCases.VerifySignInErrorMessage">
        <test-method is-config="true" signature="setupMethod()[pri:0, instance:homePageTestCases.VerifySignInErrorMessage@3c947bc5]" started-at="2021-02-11T21:22:47 PST" name="setupMethod" finished-at="2021-02-11T21:22:51 PST" duration-ms="4187" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupMethod -->
        <test-method signature="signinError()[pri:0, instance:homePageTestCases.VerifySignInErrorMessage@3c947bc5]" started-at="2021-02-11T21:22:51 PST" name="signinError" finished-at="2021-02-11T21:22:53 PST" duration-ms="2519" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signinError -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:homePageTestCases.VerifySignInErrorMessage@3c947bc5]" started-at="2021-02-11T21:22:53 PST" name="tearDown" finished-at="2021-02-11T21:22:54 PST" duration-ms="244" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setupMethod()[pri:0, instance:homePageTestCases.VerifySignInErrorMessage@3c947bc5]" started-at="2021-02-11T21:22:54 PST" name="setupMethod" finished-at="2021-02-11T21:22:57 PST" duration-ms="3200" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupMethod -->
        <test-method signature="signinError1()[pri:0, instance:homePageTestCases.VerifySignInErrorMessage@3c947bc5]" started-at="2021-02-11T21:22:57 PST" name="signinError1" finished-at="2021-02-11T21:22:59 PST" duration-ms="2278" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[error message is not expected expected [There ] but found [There was a problem]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: error message is not expected expected [There ] but found [There was a problem]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at homePageTestCases.VerifySignInErrorMessage.signinError1(VerifySignInErrorMessage.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signinError1 -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:homePageTestCases.VerifySignInErrorMessage@3c947bc5]" started-at="2021-02-11T21:23:00 PST" name="tearDown" finished-at="2021-02-11T21:23:00 PST" duration-ms="226" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- homePageTestCases.VerifySignInErrorMessage -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
